// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJBzNy-uNhiCVTjZ-hCFxtuRgx2Aw0rqE',
    appId: '1:313393556956:web:5311aef3a99af76854b319',
    messagingSenderId: '313393556956',
    projectId: 'wsecure',
    authDomain: 'w-52931.firebaseapp.com',
    storageBucket: 'wsecure.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNMrBEr-QAGYdpkVf-wL3ehw0nULKKLk',
    appId: '1:313393556956:android:bffee7cff81f4add54b319',
    messagingSenderId: '313393556956',
    projectId: 'wsecure',
    storageBucket: 'wsecure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YEP7N6iItWvdxyad9sFSkmo4HnFUjlI',
    appId: '1:313393556956:ios:2861211da10ae44254b319',
    messagingSenderId: '313393556956',
    projectId: 'wsecure',
    storageBucket: 'wsecure.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0YEP7N6iItWvdxyad9sFSkmo4HnFUjlI',
    appId: '1:313393556956:ios:2861211da10ae44254b319',
    messagingSenderId: '313393556956',
    projectId: 'wsecure',
    storageBucket: 'wsecure.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJBzNy-uNhiCVTjZ-hCFxtuRgx2Aw0rqE',
    appId: '1:313393556956:web:68a687685925c05854b319',
    messagingSenderId: '313393556956',
    projectId: 'wsecure',
    authDomain: 'w-52931.firebaseapp.com',
    storageBucket: 'wsecure.appspot.com',
  );

}