// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIIlitoaT4ChovEaB6MxevqSplXstdEg',
    appId: '1:668768674791:web:0c83925dc3547192fed342',
    messagingSenderId: '668768674791',
    projectId: 'gothic-avenue-417610',
    authDomain: 'gothic-avenue-417610.firebaseapp.com',
    storageBucket: 'gothic-avenue-417610.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGRSM-Us-kthLfz4yBSvetH-wBa-o7klk',
    appId: '1:668768674791:android:372504fc6590af6afed342',
    messagingSenderId: '668768674791',
    projectId: 'gothic-avenue-417610',
    storageBucket: 'gothic-avenue-417610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP792CG_f6DcficIZrbSjCddUd4l_9mSg',
    appId: '1:668768674791:ios:c10722102ed6ffa6fed342',
    messagingSenderId: '668768674791',
    projectId: 'gothic-avenue-417610',
    storageBucket: 'gothic-avenue-417610.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP792CG_f6DcficIZrbSjCddUd4l_9mSg',
    appId: '1:668768674791:ios:c10722102ed6ffa6fed342',
    messagingSenderId: '668768674791',
    projectId: 'gothic-avenue-417610',
    storageBucket: 'gothic-avenue-417610.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChIIlitoaT4ChovEaB6MxevqSplXstdEg',
    appId: '1:668768674791:web:cb9725985de78e88fed342',
    messagingSenderId: '668768674791',
    projectId: 'gothic-avenue-417610',
    authDomain: 'gothic-avenue-417610.firebaseapp.com',
    storageBucket: 'gothic-avenue-417610.appspot.com',
  );
}
